name: Document-Q-A-LLM
description: A powerful Streamlit application for document question-answering using RAG with local LLM processing
topics:
  - artificial-intelligence
  - document-analysis
  - nlp
  - qa-system
  - rag
  - streamlit
  - vector-database
  - llm
  - pdf-processing
  - ollama
  - government-schemes
  - chromadb
  - natural-language-processing
  - document-qa
  - chatbot
